# Generated by Django 3.2 on 2024-03-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(blank=True, max_length=500)),
                ('Message_Creation_Date', models.DateField(auto_now_add=True)),
                ('Message_Edit_Date', models.DateField(auto_now=True)),
            ],
        ),
    ]
