# Generated by Django 3.2 on 2024-05-28 11:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Users_list_id', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=list, size=None)),
                ('Users_admin_list_id', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=list, size=None)),
                ('Group_name', models.CharField(max_length=100)),
                ('Group_desc', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MessageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(blank=True, max_length=500)),
                ('Message_Creation_Date', models.DateField(auto_now_add=True)),
                ('Message_Edit_Date', models.DateField(auto_now=True)),
                ('Chat_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messanges.chat')),
                ('Group_chat_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messanges.groupchat')),
            ],
        ),
    ]
