# Generated by Django 3.2 on 2024-06-07 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messanges', '0004_mediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='Chat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messanges.chat'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='Group_chat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messanges.groupchat'),
        ),
    ]
