# Generated by Django 3.2 on 2024-05-10 03:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_line_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friend_list_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=list, size=None),
        ),
    ]
